services:
  frontend:
    init: true
    restart: always
    build:
      context: ./frontend
    environment:
      NODE_ENV: production
    ports:
      - "8080:8080"
  algorithms:
    build:
      context: algorithms
    ports:
      - "8000:80"
    depends_on:
      postgres:
        condition: service_healthy
      elasticsearch:
        condition: service_started
    environment:
      HF_HOME: /.cache
      DATABASE_URL: postgresql://user:password@postgres:5432/mydatabase
      ELASTICSEARCH_URL: http://elasticsearch:9200
    volumes:
      - ./elastic_cache:/.cache
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.21
    environment:
      - discovery.type=single-node
    volumes:
      - ./elastic_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"
  postgres:
    image: postgres:13
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U user -d mydatabase || exit 1" ]
      interval: 10s
      timeout: 5s
      retries: 5
