class FB_ENV_VARS:
    TOTP_KEY = "TOTP_KEY"
    KAFKA_BOOTSTRAP_SERVERS = "KAFKA_BOOTSTRAP_SERVERS"
    DATA_LAYER_URL = "DATA_LAYER_URL"
    VALIDATION_EMAIL = "VALIDATION_EMAIL"
    API_URL = "API_URL"
    VALIDATION_EMAIL_KEY = "VALIDATION_EMAIL_KEY"
