services:
  db:
    build: .
    container_name: postgres_db
    restart: always
    env_file:
      - path: ../.env
        required: true
    ports:
      - "9999:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
