services:
  db:
    image: postgres:16.3
    restart: always
    env_file:
      - path: ../.env
        required: true
    ports:
      - "${DB_PORT:-9999}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
