apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend-reverse-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend-reverse-proxy
  template:
    metadata:
      labels:
        app: backend-reverse-proxy
    spec:
      containers:
        - name: backend-reverse-proxy
          image: ghcr.io/matt-lebl/uvic-marketplace/backend-reverse-proxy:063bc09
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8000
          env:
            - name: FB_URL
              value: "http://backend-fastapi:8001"
            - name: FA_URL
              value: "http://algorithms-fastapi:8004"
      imagePullSecrets:
        - name: github-container-registry
