apiVersion: v1
kind: Service
metadata:
  name: elastic
spec:
  selector:
    app: elastic
  ports:
    - protocol: TCP
      port: 9200
      name: port-one
    - protocol: TCP
      port: 9300
      name: port-two
