apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: ghcr.io/matt-lebl/uvic-marketplace/frontend:986c151
          imagePullPolicy: Always
          ports:
            - containerPort: 8080
          env:
            - name: port
              value: "8080"
            - name: REACT_APP_BASEURL
              value: https://market.lebl.ca
      imagePullSecrets:
        - name: github-container-registry

