apiVersion: v1
kind: Service
metadata:
  name: kafka
spec:
  selector:
    app: kafka
  ports:
    - protocol: TCP
      port: 9092
      name: port-one
    - protocol: TCP
      port: 19092
      name: port-two
    - protocol: TCP
      port: 29093
      name: port-three
