services:
  fastapi:
    build: 
      context: . # The algorithms directory
      dockerfile: ./app/api/Dockerfile
    command: "./entrypoint.sh"
    ports:
      - "8000:80"
    depends_on:
      db: 
        condition: service_healthy
      elasticsearch:
        condition: service_started
    environment:
      HF_HOME: /.cache
      #DATABASE_URL: postgresql://user:password@db:5432/mydatabase
      POSTGRES_SCHEME: postgresql://
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_HOST: db
      POSTGRES_PORT: 5432
      POSTGRES_NAME: mydatabase

      ELASTICSEARCH_URL: http://elasticsearch:9200
    volumes:
      - ./elastic_cache:/.cache

  kafka-consumer:
    build:
      context: . # The algorithms directory
      dockerfile: ./app/kafka/Dockerfile
    depends_on:
      elasticsearch:
        condition: service_started
    ports:
      - 29092:9092
    environment:
      KAFKA_BOOTSTRAP_SERVERS: 70.66.242.15:29092
      KAFKA_TOPICS: create-listing delete-listing update-listing view-listing create-user edit-user delete-user
      DATABASE_URL: postgresql://user:password@db:5432/mydatabase
      ELASTICSEARCH_URL: http://elasticsearch:9200

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.17.21
    environment:
      - discovery.type=single-node
    volumes:
      - ./elastic_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
      - "9300:9300"

  db:
    image: postgres:13
    volumes:
      - ./postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: mydatabase
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U user -d mydatabase || exit 1"]
      interval: 10s
      timeout: 5s
      retries: 5

 # For testing locally 
  tests:
    build: 
      context: . # The algorithms directory
      dockerfile: ./app/api/Dockerfile
    environment:
      - ELASTICSEARCH_URL=http://elasticsearch:9200
      - DATABASE_URL=postgresql://user:password@db:5432/mydatabase
      - KAFKA_BOOTSTRAP_SERVERS=70.66.242.15:29092
    command: >
      sh -c "sleep 10 && pytest -v"
    volumes:
      - .:/code
    depends_on:
      - fastapi
      - db
      - elasticsearch
