"""update user with see_charity_items and blacklisted_items

Revision ID: 4817ac0489b5
Revises: 63413538efb9
Create Date: 2024-07-25 00:39:54.859374

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4817ac0489b5'
down_revision: Union[str, None] = '63413538efb9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('see_charity_items', sa.Boolean(), nullable=True))
    op.add_column('users', sa.Column('blacklisted_items', postgresql.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', 'blacklisted_items')
    op.drop_column('users', 'see_charity_items')
    # ### end Alembic commands ###
    