name: Deploy Reverse Proxy

on:
  push:
    branches:
      - master
      - develop
    paths:
      - 'backend/reverse-proxy/**'

permissions:
  contents: read
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Cache Docker layers
        uses: actions/cache@v3
        with:
          path: /tmp/.buildx-cache
          key: ${{ runner.os }}-buildx-${{ github.sha }}
          restore-keys: |
            ${{ runner.os }}-buildx-

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Extract commit hash
        id: get_commit
        run: echo "::set-output name=hash::$(echo ${{ github.sha }} | cut -c1-7)"

      - name: Build and push Docker image
        run: |
          docker build -t ghcr.io/${{ github.repository }}/backend-reverse-proxy:${{ steps.get_commit.outputs.hash }} --platform=linux/amd64 backend/reverse-proxy/
          docker push ghcr.io/${{ github.repository }}/backend-reverse-proxy:${{ steps.get_commit.outputs.hash }}

      - name: Verify image in GitHub Container Registry
        run: |
          echo "Image built and pushed: ghcr.io/${{ github.repository }}/backend-reverse-proxy:${{ steps.get_commit.outputs.hash }}"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Set the kubernetes context
        uses: azure/k8s-set-context@v2
        with:
          method: service-account
          k8s-url: https://91.107.206.247:6443
          k8s-secret: ${{ secrets.KUBE_SECRET }}
      - name: Checkout source code
        uses: actions/checkout@v3
      - name: Extract commit hash
        id: get_commit
        run: echo "::set-output name=hash::$(echo ${{ github.sha }} | cut -c1-7)"
      - name: Deploy to the Kubernetes cluster
        uses: azure/k8s-deploy@v1
        with:
          namespace: default
          manifests: |
            kubernetes-configuration/backend-reverse-proxy-deployment.yaml
          images: |
            ghcr.io/${{ github.repository }}/backend-reverse-proxy:${{ steps.get_commit.outputs.hash }}