name: Algorithms Service Lint

on:
  push:
    paths:
      - 'algorithms/**'

jobs:
  lint:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ./algorithms

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: 3.9
          cache: 'pip'

      - name: Perform Linting
        uses: chartboost/ruff-action@v1