name: TruffleHog Secret Scan

on:
  push:
    branches:
      - develop
      - master
      - resops/workflow-test
  pull_request:
    branches:
      - develop
      - master

jobs:
  TruffleHog_Scan:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Secret Scan
        run: |
          trufflehog --json filesystem . > trufflehog-report.json
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

      - name: Upload Trufflehog Report
        uses: actions/upload-artifact@v2
        with:
          name: trufflehog-report
          path: trufflehog-report.json
